### ISSUE TITLE
Cacheserver upload failed because of a database error

### ISSUE THREAD

**Issue by keithoconor** [Unity-Technologies/unity-cache-server#13]
I'm getting this error any time I import (or reimport) a video asset: 
Cacheserver upload failed because of a database error: 'Assets/Video.mp4'

I'm at the latest version of unity-cache-server at the time of this post, and testing with Unity 2017.1.0f3. The issue can be reproduced with the congo.mp4 video that ships with Unity (found here: C:\Program Files\Unity\2017.1.0f3\Editor\Data\UnityExtensions\Unity\VR\iOS\GVRSDK\Pods\GVRSDK\copy\VideoWidgetDemo\resources\congo.mp4).

Other than this issue, the cache server has been working well for everyone on the network.

**Comment by stephen-palmer** [comment]
This is a client-side error (in Unity), not a server problem. Suggest filing a bug report via the Unity bug reporter.

**Comment by IJsLauw** [comment]
Same problem here, has there been a bug filed yet?

Connect to CacheServer 10.10.3.14:8126
 -- No matching cache server file found on server 'Assets/TouchTable/Video/city_scene3.mp4' (GUID: 0d4d10b0a2b3b8949b612f54d54c3879 HASH: 01e5085489653f05534d30e8b50ba75d)

Updating Packages - GUID: 00000000000000001000000020000000...
 done. [Time: 13.682604 ms] 
Unloading 2826 Unused Serialized files (Serialized files now loaded: 0)
System memory in use before: 130.1 MB.
System memory in use after: 130.0 MB.

Unloading 2826 unused Assets to reduce memory usage. Loaded Objects now: 1677.
Total: 6.875245 ms (FindLiveObjects: 2.034057 ms CreateObjectMapping: 0.568647 ms MarkObjects: 3.396311 ms  DeleteObjects: 0.868895 ms)

Updating Assets/TouchTable/Video/city_scene3.mp4 - GUID: 0d4d10b0a2b3b8949b612f54d54c3879...
----- Compute hash for Assets/TouchTable/Video/city_scene3.mp4.
Disconnect from CacheServer
Cacheserver upload failed because of a database error: 'Assets/TouchTable/Video/city_scene3.mp4'
 
(Filename: C:\buildslave\unity\build\Modules/AssetDatabase/Editor/V1/CacheServer/CacheServer.cpp Line: 635)

**Comment by bjornustwo** [comment]
@IJsLauw @keithoconor Did you find a fix / workaround for this?

**Comment by todds-unity** [comment]
@bjornustwo : There is an issue filed for this problem.

There is a note in the issue description that states:

> Note: You can fix the issue by enabling and disabling transcoding.
