### ISSUE TITLE
[v6.4]Ineffective mark-compacts near heap limit Allocation failed

### ISSUE THREAD

**Issue by z5616342** [Unity-Technologies/unity-cache-server#141]
version：6.4
I still have this error.
WARNING:NODE_APP_INSTANCE value of '0' did not match any instance config file names.
FARAL ERROR : Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory。
How can I solve this problem?

**Comment by timezombi** [comment]
I also experienced this problem on version 6.4.0 beta 3, even with significant amounts of RAM increased for max-old-space-size. The full error stack trace looks like this...

> <--- Last few GCs --->
> 
> [17055:0x2b2b230] 595567385 ms: Scavenge 23820.4 (24852.5) -> 23819.5 (24852.5) MB, 123.0 / 0.0 ms  (average mu = 0.151, current mu = 0.078) allocation failure
> [17055:0x2b2b230] 595567576 ms: Scavenge 23820.4 (24852.5) -> 23819.5 (24852.5) MB, 115.6 / 0.0 ms  (average mu = 0.151, current mu = 0.078) allocation failure
> [17055:0x2b2b230] 595567718 ms: Scavenge 23820.5 (24852.5) -> 23819.8 (24852.5) MB, 115.5 / 0.0 ms  (average mu = 0.151, current mu = 0.078) allocation failure 

> FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
>  1: 0x8f9d10 node::Abort() [node]
>  2: 0x8f9d5c  [node]
>  3: 0xaffd0e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
>  4: 0xafff44 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
>  5: 0xef4152  [node]
>  6: 0xef4258 v8::internal::Heap::CheckIneffectiveMarkCompact(unsigned long, double) [node]
>  7: 0xf00332 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [node]
>  8: 0xf00c64 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
>  9: 0xf0143a v8::internal::Heap::FinalizeIncrementalMarkingIfComplete(v8::internal::GarbageCollectionReason) [node]
> 10: 0xf04b17 v8::internal::IncrementalMarkingJob::Task::RunInternal() [node]
> 11: 0xbf5d36 v8::internal::CancelableTask::Run() [node]
> 12: 0x980e74 node::PerIsolatePlatformData::RunForegroundTask(std::unique_ptr<v8::Task, std::default_delete<v8::Task> >) [node]
> 13: 0x982552 node::PerIsolatePlatformData::FlushForegroundTasksInternal() [node]
> 14: 0xa6ee8f  [node]
> 15: 0xa80738  [node]
> 16: 0xa6f7cb uv_run [node]
> 17: 0x904525 node::Start(v8::Isolate*, node::IsolateData*, std::vector<std::string, std::allocator<std::string> > const&, std::vector<std::string, std::allocator<std::string> > const&) [node]
> 18: 0x90272c node::Start(int, char**) [node]
> 19: 0x7f906b775830 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
> 20: 0x8bbc65  [node]

**Comment by timezombi** [comment]
@z5616342 I tried to provide some extra information yesterday to hopefully help shed some light for Unity but the Out-of-Memory errors have been a pervasive problem for many months. 

The "workaround" I use is to run unity-cache-server in a wrapper script that automatically restarts the unity-cache-server process whenever it hard crashes from OOM errors. One of the additional measure we take that has helped a lot is to increase the max-old-space-size to a much larger number than the default. You can increase the max-old-space-size by running the unity-cache-server  main js file with node. 

On my system, the unity-cache-server invocation looks like this in my wrapper script which gives the max-old-space-size 25,000MB:

`node --max-old-space-size=25000 /usr/local/bin/unity-cache-server`

It seems to eventually crash no matter how much space I give it but it seems to happen much less frequently than sticking with the default size for the very large project I'm working on.

If you want the maintainers to help you, it helps to post your config here:
`node main.js --dump-config`

In addition to the cache server version, it would probably help to post what OS you are running and what version of node you are using. You can find the node version by running `node --version`.

If you don't want to convert unity-cache-server to run as a systemd service and you are running unity-cache-server in a shell environment, then I can post my wrapper script here. It adds timestamps to the Unity Logs, restarts unity-cache-server whenever it exits with a non-zero exit status code, and it sends out an email alert with some basic stats whenever there is a failure.

Let me know if you are interested. It is totally my own creation, not supported by Unity, and it is definitely a band-aid instead of a real solution, but I have found it very useful.

**Comment by z5616342** [comment]
@timezombi Thank you for your reply，I am looking forward to seeing your wrapper script，My app is deployed on centos，node v10.16.0，I started my unity-cache-server by pm2,It has been running for 45 hours until now.
My startup script：pm2 start /home/tz/data/node/unity-cache-server/main.js --node-args="--max-old-space-size=4096" --name myApp --watch -i max
I recommend that you try to run the unity-cache-server by pm2.

**Comment by timezombi** [comment]
Alright, here the wrapper script I use. You will have to modify it slightly to work with pm2, replacing the unity-cache-server invocation with your startup script line. You will also have to change some of the directories or make sure you have proper write permissions/ownership set up for the `/var/log/unity-cache-server` directory.

The email alert I have set up requires that the "mail" command actually works. 

Essentially, the script continuously runs Unity Cache Server in a loop. If Unity Cache Server exits with a status other than 0, it just sends an email to our Pager Duty and starts up unity-cache-server again. It creates a new log file based on the timestamp whenever it starts up unity-cache-server.

The script creates 2 different log files, one for stdout and the other for stderr. I have not used pm2 before, but stderr captures the error output from node while stdout captures all the errors and transactions at the application level. Hopefully pm2 also passes stderr from node in the same way.

The wrapper script can be found at the following gist:
https://gist.github.com/timezombi/a3a92cd616684f75a5c46a412336249f

It's a pretty primitive script, but it has been significantly better than just having Unity Cache Server crash and remain offline until you start it up again. If you encounter some sort of error where unity-cache-server crashes immediately after running, then you will get sent hundreds of alerts... 😦 

I had not heard of pm2 until just now. It looks pretty cool! I'll see about using it when I upgrade to 6.4.0 beta 4 this weekend.

I hope this helps save you from some hardships! Good luck!

**Comment by z5616342** [comment]
@timezombi  thanks very much, I think I have solved this problem by this way    " --max-old-space-size=4096", I have not reported this error until now.
