### ISSUE TITLE
the file 'memorystream' is corrupted!remove it and launch unity again

### ISSUE THREAD

**Issue by devTimer** [Unity-Technologies/unity-cache-server#148]
i was test in my project,when i switch to windows and android,it's ok.but when i switch to iphone,the error come out.restart unity can't fix it.clear library folder can't fix it.what i can do?

**Comment by BrettKercher** [comment]
https://answers.unity.com/questions/1117177/the-file-memorystream-is-corrupted-remove-it-and-l.html

Sorry for the late response, but I found this post with a user having the same issue. If this is still a problem for you, could you try the solution suggested in that thread?

Otherwise, this appears to be an editor problem more than a Cache Server problem, but just to make sure you could also try running the cache clean command (https://github.com/Unity-Technologies/unity-cache-server#cache-cleanup) to see if that helps.
