### ISSUE TITLE
--NODE_CONFIG_DIR is ignored

### ISSUE THREAD

**Issue by maguro** [Unity-Technologies/unity-cache-server#164]
The command line option `--NODE_CONFIG_DIR` is ignored.  Setting the environmental property `NODE_CONFIG_DIR` seems to work.

**Comment by BrettKercher** [comment]
Looking back at the commit that option was added, it appears it's always just been ignored. And it's apparently not a popular option, since it's been a couple years and you seem to be the first one to notice!
We're actually initializing the config settings before parsing the command line options, since we use the config values to fill in default command line options, so instead of refactoring that logic, I'll go ahead and remove the option and reword the README file to encourage using the environment variable instead.

**Comment by BrettKercher** [comment]
Resolved with #167
