### ISSUE TITLE
"expected type of response from cache server" error

### ISSUE THREAD

**Issue by kungfubozo** [Unity-Technologies/unity-cache-server#67]
hi 
since we upgraded to cache server v6, 
we been getting below error once in a while, 

this error usually show at the beginning of unity build process (after validating cache content), and once disconnected, unity editor will never re-connect to cache server again in the session

is there something we need to do ? thanks

` 
-- No matching cache server file found on server 'Assets/xyz.jpg' (GUID: 70cfc74b0db6d4c4eaff04f2b46aa81b HASH: e6ca3ed47c341e2559e0d0850ccb4bd6)
Wrong assetInfo identifier
Did not get expected type of response from cache server
Cacheserver download failed because of a connection error: 'Assets/abc.fbx'

(Filename: /Users/builduser/buildslave/unity/build/Editor/Src/AssetPipeline/CacheServer/CacheServer.cpp Line: 465)

Disconnect from CacheServer
Updating Assets - GUID: 00000000000000001000000000000000...
 done. [Time: 25.597315 ms]
Unloading 19 Unused Serialized files (Serialized files now loaded: 0)
`

**Comment by stephen-palmer** [comment]
Haven't seen this before. It seems like you may have some out of date cache server data, perhaps because your Unity version has changed?

If it's not too much of a headache, I would wipe the cache and start fresh. You can use the provided tools to re-seed the cache server from a locally imported project if you want to get back to a fully seeded cache quickly.

**Comment by kungfubozo** [comment]
unfortuately, we actually have multiple branch of (mostly) same project being built by various version of unity (54, 56, 2017, 2018) simultaneously... if unity version is an issue then this could be a problem. this error does not show up with older cache server using same workflow. 

As as a side suggestion, it actually would be great if cache server can have separate 'repository' for major unity version as a safe guard. we did got bite once ;-p

**Comment by stephen-palmer** [comment]
We do not recommend mixing major unity versions on the same cache server. Especially from 5.6 -> 2018 for the same project across branches that will have matching asset GUIDs, you are almost certainly going to run into trouble (as you have already).

**Comment by kungfubozo** [comment]
hmm thanks.
but wondering, in that case, what is the expected usage of cache server ? 

bc in unity, there is only 1 common setting across all version for cache server. so even if we set up different instance of cache server (whether ip or port#). if we want to automatically set the right setting for all users, we would have to do it through c# script -- which means it can potentially not compile/runs correctly for some scenerio, esp if he has other script in place that cause ./Editor script compile error? thx again

**Comment by stephen-palmer** [comment]
Correct, the cache server setting is global. Instead of setting this value by script, you can instead launch Unity with a command line option to connect to a specific cache server. You can also open a specific project at a path. Here are the relevant commands from the [User Manual](https://docs.unity3d.com/Manual/CommandLineArguments.html):

Command|Details
----|----
**-CacheServerIPAddress \<host:port\>**|Connect to the specified Cache Server on startup, overriding any configuration stored in the Editor Preferences. Use this to connect multiple instances of Unity to different Cache Servers.
**-projectPath \<pathname\>**| 	Open the project at the given path.

So in your situation you can setup shortcuts to launch Unity connected to the correct cache server for each branch of the project.

**Comment by stephen-palmer** [comment]
No, unfortunately, it's not possible as the client (Editor) does not send any identifying information to the cache server.

**Comment by msiebuhr** [comment]
@kungfubozo We've been looking at the same issues.

Our biggest problem is that when we get to the part in the Unity Editor where we get to programmatically set the cache-server in settings, it has (potentially) already been used to do something with assets. That makes using different cache-servers for different projects *really* hard. I don't know if the situation is different with different versions of Unity (i.e. if they store their settings in different places, so the different versions can be set once per editor-version and then left alone).

Right now, we we run one cache server for use by our developers' machines, across all projects. Then we also run one cache-server per project, for exclusive use by our build-infrastructure (where we know what project will be built, so we can set the server address early). We still have to delete an entire cache every now and then due to weird stuff happening, but at very least the blast damage is fairly small wrt. build-times on neighboring projects.

Aslo, shameless plug:

I've written another implementation over at https://github.com/msiebuhr/ucs, which hacks in support for multiple versions by opening multiple ports (but disk-quota/GC happens across all uploaded files). One major caveat is that as it's a personal project of mine, we haven't used it in production yet. I have hooked it up to parts of our build-infrastructure, but it's not used by anyone on a daily basis.

```shell
> go get install github.com/msiebuhr/ucs/cmd/ucs
# Start on port 5054, 5056, 5017 and 5018, 50GB quota
> ucs \
  -quota 50G \
  -port unity-54:5054 \
  -port unity-56:5056 \
  -port unity-2017:5017 \
  -port unity-2018:5018
> open http://localhost:9126 # See admin-page
```

Adding more data to the connection (so the server can make some intelligent decision) has been discussed over at #31.
