### ISSUE TITLE
[Question] Still spending massive time converting

### ISSUE THREAD

**Issue by sphess** [Unity-Technologies/unity-cache-server#92]
Hello all,
I'm having trouble with Unity (2018.30f2) still converting _tons_ of texture assets even when freshly seeding the server:

1.  Open a project in Unity (on Windows), let it convert for Android.  (Total time ~30 mins.)
2.  Use the provided script to export to a Json file.
3.  Import the Json into the cache server (latest version) running on another Windows machine on the LAN.
4.  Set up Unity to point to this cache server on the LAN.
5.  Close Unity and delete the Library directory.
6.  Open the project again (choosing Android)... the progress shows that it is indeed updating from the cache server, but then it spends 25+ mins locally converting textures anyway.  This is on the same machine that seeded the server in the first place.

I feel like I'm missing something obvious?  The cache server showed that it served something like 980 mb, so it seems like a lot of data is flowing, why is so much time still spent converting?

Thanks for your time!

**Comment by timezombi** [comment]
I am by no means an expert, but I can provide some slight troubleshooting information.

Are you sure that you seeded the cache server correctly? The unity-cache-server-import command needs to be run from the same machine that generated the export. Did you make sure to do that?

Do you have any other clients connected to your Cache Server instance?

Do you have high reliability mode enabled?

Are you configuring all of your settings through a configuration file? If yes, can you post the config here?

Do you know what happens when you take a fresh cache server instance, do a full initial import of your project to seed it (don't use the JSON export, just open the project for the first time while your client is connected to Cache Server), delete your Library, then try to open the project again?
